# Adapted from https://github.com/puckel/docker-airflow
# Update details in Airflow UI for "airflow_db" connection as needed
version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"

    webserver:
        image: puckel/docker-airflow:1.8.0
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=y
            - EXECUTOR=Local
        volumes:
            - ~/src/airflow_examples/dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
